import {useEffect,useRef} from 'react';
import type {Evidence,Tag} from './types';
import {Icon} from './icons';
export function Empty({title,text}:{title:string;text:string}){return <div className="empty"><Icon name="updates" size={30}/><h3>{title}</h3><p>{text}</p></div>;}
export function ErrorBox({message,retry}:{message:string;retry?:()=>void}){return <div className="error" role="alert"><Icon name="info"/><span>{message}</span>{retry&&<button className="text-button" onClick={retry}>Try again</button>}</div>;}
export function Loading({text='Loading updates…'}:{text?:string}){return <div className="loading" role="status"><span className="spinner"/>{text}</div>;}
export function Tags({tags}:{tags:Tag[]}){return <div className="tags">{tags.map(t=><span className="tag" key={t.id}>{t.name}</span>)}</div>;}
export function EvidenceLinks({evidence,ids}:{evidence:Evidence[];ids?:string[]}){const selected=ids?evidence.filter(e=>ids.includes(e.evidence_id)):evidence;const groups=new Map<string,Evidence>();for(const e of selected.filter(x=>x.url)){const key=`${e.url}:${e.pdf_page_end}`;const prior=groups.get(key);groups.set(key,prior?{...prior,locator:prior.locator+"; "+e.locator}:e);}const links=[...groups.values()];return <div className="evidence-links">{links.map(e=><a key={e.evidence_id} href={e.url!} target="_blank" rel="noreferrer" title={e.locator}><Icon name="documents" size={13}/>p. {e.pdf_page_start}{e.pdf_page_end!==e.pdf_page_start?`–${e.pdf_page_end}`:''}<span className="sr-only"> — {e.locator}</span></a>)}</div>;}
export function Modal({title,children,close}:{title:string;children:React.ReactNode;close:()=>void}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const old=document.activeElement as HTMLElement;ref.current?.showModal();return()=>{old?.focus();};},[]);return <dialog ref={ref} className="modal" onCancel={e=>{e.preventDefault();close();}} onClick={e=>{if(e.target===e.currentTarget)close();}} aria-label={title}><header><h2>{title}</h2><button className="icon-button" onClick={close} aria-label="Close dialog"><Icon name="close"/></button></header>{children}</dialog>;}
