import {useRef,useState} from 'react';
import type {Concept,Profile} from './types';
import {api,post,profileName} from './model';
import {ErrorBox,Modal} from './common';
import {PracticeTree} from './PracticeTree';
import {Icon} from './icons';
export function CreateProfile({current,profiles,concepts,close,created}:{current:Profile;profiles:Profile[];concepts:Concept[];close:()=>void;created:(p:Profile)=>void}){
 const [name,setName]=useState(''),[copy,setCopy]=useState(true),[selected,setSelected]=useState<string[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');const lock=useRef(false),id=useRef('profile-'+crypto.randomUUID());
 async function save(){if(lock.current)return;const clean=name.trim();if(!clean){setError('Give this profile a name.');return;}if(profiles.some(p=>profileName(p).toLowerCase()===clean.toLowerCase()||p.name.toLowerCase()===clean.toLowerCase())){setError('Choose a different name so the profiles are easy to distinguish.');return;}if(!copy&&!selected.length){setError('Select at least one practice branch.');return;}lock.current=true;setBusy(true);setError('');try{const p:Profile={id:id.current,name:clean,rules:copy?structuredClone(current.rules):selected.map((t,i)=>({id:'practice-'+i,all_of:[t]})),exclude:copy?[...current.exclude]:[]};created(await api<Profile>('/profiles',post(p)));}catch(e){setError((e as Error).message);}finally{lock.current=false;setBusy(false);}}
 return <Modal title="Create a profile" close={()=>{if(!busy)close();}}><div className="create-profile-form"><label className="profile-name-label">Profile name<input autoFocus aria-label="Profile name" maxLength={80} value={name} disabled={busy} onChange={e=>setName(e.target.value)} placeholder="e.g. IPO & listed companies"/></label><p className="profile-name-help">A separate set of interests and saved updates. Choose a name that describes the work.</p><fieldset className="profile-start"><legend>How would you like to start?</legend><label><input type="radio" name="profile-start" checked={copy} disabled={busy} onChange={()=>setCopy(true)}/><span><strong>Use {profileName(current)} as a starting point</strong><small>Copy its saved interests and exclusions. You can edit them next.</small></span></label><label><input type="radio" name="profile-start" checked={!copy} disabled={busy} onChange={()=>setCopy(false)}/><span><strong>Choose practices from the tree</strong><small>Start a fresh profile with the branches you tick.</small></span></label></fieldset>{!copy&&<PracticeTree concepts={concepts} selected={selected} onChange={setSelected}/>}<p className="footnote">Creating this profile leaves existing profiles unchanged. It does not send notifications.</p>{error&&<ErrorBox message={error}/>}</div><footer className="modal-actions"><button className="button secondary" disabled={busy} onClick={close}>Cancel</button><button className="button primary" disabled={busy||!name.trim()||(!copy&&!selected.length)} onClick={save}>{busy?'Creating…':'Create profile'}<Icon name="plus" size={14}/></button></footer></Modal>;
}
