import {useEffect,useState,useRef} from 'react';
import type {Update,Profile,Event,Timing} from './types';
import {api,dateLabel,timeLabel,actionLabel,readable,officialLink,profileName} from './model';
import {Icon} from './icons';
import {Loading,ErrorBox,EvidenceLinks,Tags} from './common';
export function Detail({id,profile,close,onState}:{id:string;profile:Profile;close:()=>void;onState:(id:string,state:{read?:boolean;saved?:boolean})=>Promise<void>}){
 const panel=useRef<HTMLElement>(null);
 useEffect(()=>{panel.current?.querySelector<HTMLButtonElement>('[aria-label="Close update details"]')?.focus();},[]);
 const [data,setData]=useState<Update|null>(null),[error,setError]=useState(''),[tab,setTab]=useState('overview'),[eventId,setEventId]=useState(''),[busy,setBusy]=useState(false),[hash,setHash]=useState('');
 const [reload,setReload]=useState(0);
 useEffect(()=>{let active=true;setData(null);setError('');setHash('');setTab('overview');api<Update>(`/updates/${id}?profile_id=${encodeURIComponent(profile.id)}`).then(x=>{if(active){setData(x);setEventId(x.matches[0]?.event_id||x.events[0]?.id);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[id,profile.id,reload]);
 useEffect(()=>{if(tab!=='source')return;let active=true;api<{document:{pdf_sha256:string}}>(`/documents/${id}`).then(x=>{if(active)setHash(x.document.pdf_sha256);}).catch(()=>{});return()=>{active=false;};},[tab,id]);
 useEffect(()=>{function key(e:KeyboardEvent){if(e.key==='Escape'&&!document.querySelector('dialog[open]'))close();}window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[close]);
 const event=data?.events.find(e=>e.id===eventId)||data?.events[0];
 async function save(){if(!data||busy)return;setBusy(true);try{await onState(id,{saved:!data.state.saved});setData({...data,state:{...data.state,saved:!data.state.saved}});}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <aside ref={panel} className="detail" aria-label="Update details" onKeyDown={e=>{if(e.key==='Tab'&&window.innerWidth<=1000){const nodes=[...panel.current!.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],select,summary')].filter(x=>x.offsetParent!==null);const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}}><div className="detail-toolbar"><span><Icon name="documents" size={15}/> Update details</span><div className="button-row">{data&&<button className={`icon-button ${data.state.saved?'is-saved':''}`} aria-label={data.state.saved?'Unsave update':'Save update'} aria-pressed={data.state.saved} disabled={busy} onClick={save}><Icon name="bookmark"/></button>}<button className="icon-button" aria-label="Close update details" onClick={close}><Icon name="close"/></button></div></div>
 {!data?(error?<ErrorBox message={error} retry={()=>setReload(x=>x+1)}/>:<Loading text="Opening update…"/>):<><div className="detail-heading"><div className="eyebrow">{data.document_type.name} <span>·</span> {dateLabel(data.published_date)}</div><h2>{data.title}</h2><div className="detail-meta">{data.has_proposals&&<span className="badge proposed">Includes proposals</span>}<span className="quiet">{data.origin==='SAVED_CLASSIFICATION'?'Saved analysis':'New analysis'}</span><a className="source-link" href={data.source_endpoint} target="_blank" rel="noreferrer">Open source PDF <Icon name="external" size={13}/></a></div></div>
 <div className="detail-tabs" role="tablist" aria-label="Update information">{[['overview','Overview'],['matches','Why this matches'],['source','Source & review']].map(([key,label])=><button key={key} role="tab" aria-label={label} aria-selected={tab===key} onClick={()=>setTab(key)}>{label}{key==='matches'&&data.matches.length>0&&<span className="small-count">{data.matches.length}</span>}</button>)}</div>
 <div className="detail-body" role="tabpanel" aria-label={tab==='overview'?'Overview':tab==='matches'?'Why this matches':'Source and review'}>{error&&<ErrorBox message={error}/>}
 {tab==='overview'&&event&&<>{data.events.length>1&&<div className="provision-selector"><label htmlFor="provision">Provision {data.events.indexOf(event)+1} of {data.events.length}</label><select id="provision" value={event.id} onChange={e=>setEventId(e.target.value)}>{data.events.map((e,i)=><option key={e.id} value={e.id}>{i+1}. {e.title}</option>)}</select></div>}<EventView event={event}/></>}
 {tab==='matches'&&<><p className="intro">Relevance to <strong>{profileName(profile)}</strong>, based on your saved interests.</p>{data.matches.length===0?<div className="inset"><h3>No subscription match</h3><p>This update is available in All updates. None of your current interest groups matches its provisions.</p></div>:data.matches.map((m,i)=><section className="match-card" key={m.rule_id+m.event_id}><div className="eyebrow">Match {i+1} · Interest group</div><Tags tags={m.subscriptions}/><h3>{m.event_title}</h3><p>{m.reason}</p><div className="caption">Relevant classification</div><Tags tags={m.tags}/><EvidenceLinks evidence={m.evidence||[]}/><button className="text-button" onClick={()=>{setEventId(m.event_id);setTab('overview');}}>Read this provision <Icon name="arrow" size={14}/></button></section>)}<p className="footnote">Each group matches within a single provision. Broader interests include their subtopics; exclusions take priority.</p></>}
 {tab==='source'&&<><section><h3>Official source</h3><p className="source-number">{data.document_number||'Document number not stated'}</p><dl className="metadata"><div><dt>Published / issued</dt><dd>{dateLabel(data.published_date)}</dd></div><div><dt>Document type</dt><dd>{data.document_type.name}</dd></div></dl><div className="button-row wrap"><a className="button secondary" target="_blank" rel="noreferrer" href={data.source_endpoint}><Icon name="documents" size={16}/> Preserved PDF <Icon name="external" size={13}/></a>{officialLink(data.official_url)&&<a className="button secondary" href={officialLink(data.official_url)!} target="_blank" rel="noreferrer">SEBI source <Icon name="external" size={13}/></a>}</div></section><section><h3>Review information</h3><p>{data.review.quality_level==='HUMAN_LEGAL_REVIEWED'?'Gold — human approved':'Model reviewed'} · {data.origin==='SAVED_CLASSIFICATION'?'Saved analysis':'Generated analysis'}</p><p className="muted">{data.review.independent_legal_review?'Human legal review is recorded.':'Independent legal review is not recorded.'}</p>{data.review.reviewed_at&&<p className="muted">Reviewed {dateLabel(data.review.reviewed_at.slice(0,10))}</p>}<details className="technical"><summary>File integrity</summary><p className="muted">SHA-256 identifies the exact preserved PDF.</p><code>{hash||'Loading file identifier…'}</code></details></section><section><h3>Evidence by provision</h3>{data.events.map(e=><details key={e.id} className="proof-group"><summary>{e.title}</summary>{e.evidence?.map(p=><div className="proof" key={p.evidence_id}><a href={p.url||data.source_endpoint} target="_blank" rel="noreferrer">Page {p.pdf_page_start}{p.pdf_page_end!==p.pdf_page_start?`–${p.pdf_page_end}`:''} · {p.locator} <Icon name="external" size={12}/></a>{p.quote?<blockquote>{p.quote}</blockquote>:<p>{p.supporting_text}</p>}<span className="caption">{p.quote?'Source quotation':'Reviewed source summary'}</span></div>)}</details>)}</section></>}
 </div></>}
 </aside>;
}
function TimingView({label,timing,event,proposed=false}:{label:string;timing:Timing;event:Event;proposed?:boolean}){return <div className="date-entry"><Icon name="clock" size={17}/><div><div className="caption">{proposed?'Proposed ':''}{label}</div><strong>{timeLabel(timing)}</strong>{timing.raw_text&&<p>{timing.raw_text}</p>}{timing.conditions?.map((c,i)=><p className="condition" key={i}>{c}</p>)}<EvidenceLinks evidence={event.evidence||[]} ids={timing.evidence_ids}/></div></div>;}
function EventView({event:e}:{event:Event}){const proof=e.evidence||[];return <>
 {e.proposed&&<div className="proposal-note"><Icon name="info"/><span>Proposed change. This provision is not an operative requirement.</span></div>}
 <section><div className="section-title"><h3>What changed</h3><span className={`importance ${e.importance==='IMP_HIGH'||e.importance==='IMP_CRITICAL'?'important':''}`}>{readable(e.importance||'Information')}</span></div><h4>{e.title}</h4><p className="position">{e.position||e.summary}</p><EvidenceLinks evidence={proof}/><Tags tags={e.topics||[]}/></section>
 {!!e.parties?.length&&<section><h3>Affected parties</h3>{e.parties.map((p,i)=><div className="party" key={i}><strong>{p.name}</strong><p>{p.scope}</p>{p.applicability==='MATERIAL_SECONDARY'&&<span className="caption">Secondary relevance</span>}</div>)}</section>}
 <section><h3>Actions</h3>{e.actions?.length?e.actions.map((a,i)=><div className="action" key={i}><span className={`badge ${a.mode==='PROPOSED'?'proposed':''}`}>{actionLabel(a)}</span><p>{a.description}</p><EvidenceLinks evidence={proof} ids={a.evidence_ids}/></div>):<p className="muted">No separate action is recorded for this provision.</p>}</section>
 <section><h3>Dates & timing</h3>{e.commencement&&<TimingView label="Commencement" timing={e.commencement} event={e} proposed={e.proposed}/>}{e.deadlines?.map(d=><div key={d.deadline_id}><TimingView label={d.kind==='CONSULTATION'?'Response deadline':d.kind==='COMPLIANCE'?'Compliance deadline':readable(d.kind)+' date'} timing={d.timing} event={e} proposed={d.mode==='PROPOSED'}/><p className="deadline-obligation">{d.obligation}{!d.mandatory?' · Optional participation':''}</p></div>)}{!e.deadlines?.length&&<p className="muted">No separate deadline is recorded.</p>}</section>
 {!!e.transitions?.length&&<section><h3>Transition provisions</h3>{e.transitions.map((t,i)=><div className="party" key={i}><strong>{t.affected_cohort}</strong><p>{t.condition}</p><p>{t.rule}</p><EvidenceLinks evidence={proof} ids={t.evidence_ids}/></div>)}</section>}
 {!!e.effects?.length&&<section><h3>Effect on the framework</h3>{e.effects.map((x,i)=><div className="effect" key={i}><p>{x.description}</p>{x.savings_or_limitations&&<p className="muted">{x.savings_or_limitations}</p>}<EvidenceLinks evidence={proof} ids={x.evidence_ids}/></div>)}</section>}
 {!!e.uncertainties?.length&&<section className="review-note"><h3>Points to check</h3>{e.uncertainties.map((u,i)=><p key={i}>{String(u.description||u.issue||u.reason||Object.values(u).filter(v=>typeof v==='string').slice(1).join(' · '))}</p>)}</section>}
 </>;}
