import {useEffect,useMemo,useRef,useState} from 'react';
import type {Concept} from './types';
import {Icon} from './icons';
export function PracticeTree({concepts,selected,onChange}:{concepts:Concept[];selected:string[];onChange:(ids:string[])=>void}){
 const practices=useMemo(()=>concepts.filter(c=>c.family==='Practice'),[concepts]);
 const byId=useMemo(()=>new Map(practices.map(c=>[c.tag_id,c])),[practices]);
 const [q,setQ]=useState(''),[expanded,setExpanded]=useState<Set<string>>(()=>new Set(practices.filter(c=>(c.level||1)<=2).map(c=>c.tag_id)));
 function ancestors(id:string){const result:string[]=[];let p=byId.get(id)?.parent;while(p&&!result.includes(p)){result.push(p);p=byId.get(p)?.parent;}return result;}
 function contains(c:Concept):boolean{return !q||(c.display_name+' '+(c.definition||'')).toLowerCase().includes(q.toLowerCase())||practices.filter(x=>x.parent===c.tag_id).some(contains);}
 function choose(id:string,checked:boolean){if(checked)onChange([...selected.filter(t=>t!==id&&!ancestors(t).includes(id)),id]);else onChange(selected.filter(t=>t!==id&&!ancestors(t).includes(id)));}
 function row(c:Concept,depth:number){if(!contains(c))return null;const kids=practices.filter(x=>x.parent===c.tag_id),parent=ancestors(c.tag_id).find(id=>selected.includes(id)),checked=!!parent||selected.includes(c.tag_id),partial=!checked&&selected.some(id=>ancestors(id).includes(c.tag_id)),open=!!q||expanded.has(c.tag_id);return <li key={c.tag_id}><div className={`practice-tree-row ${checked?'checked':''}`} style={{'--depth':depth} as React.CSSProperties}>{kids.length?<button type="button" className="tree-expand" aria-label={`${open?'Collapse':'Expand'} ${c.display_name}`} aria-expanded={open} onClick={()=>setExpanded(old=>{const next=new Set(old);if(next.has(c.tag_id))next.delete(c.tag_id);else next.add(c.tag_id);return next;})}><Icon name="chevron" size={13} style={{transform:open?'rotate(90deg)':undefined}}/></button>:<span className="tree-spacer"/>}<label className="tree-check-label"><TreeCheck name={c.display_name} checked={checked} partial={partial} disabled={!!parent} onChange={value=>choose(c.tag_id,value)}/><div className="tree-label"><strong>{c.display_name}</strong><p>{parent?`Included by ${byId.get(parent)?.display_name}`:c.definition}</p></div></label>{kids.length>0&&<span className="tree-count">{kids.length}</span>}</div>{kids.length>0&&open&&<ul>{kids.map(k=>row(k,depth+1))}</ul>}</li>;}
 return <div className="practice-tree"><div className="tree-tools"><label className="search-box"><Icon name="search" size={16}/><span className="sr-only">Search practice tree</span><input aria-label="Search practice tree" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search the full practice hierarchy…"/></label><div className="tree-tool-actions"><button type="button" className="text-button" onClick={()=>setExpanded(new Set(practices.map(c=>c.tag_id)))}>Expand all</button><button type="button" className="text-button" onClick={()=>setExpanded(new Set())}>Collapse all</button><span>{practices.length} practice categories</span></div></div><p className="tree-instructions">Tick any branches you want to follow. A parent includes all its subtopics. Different checked branches are independent interests.</p><div className="tree-scroll"><ul aria-label="Practice area hierarchy">{practices.filter(c=>!c.parent||!byId.has(c.parent)).map(c=>row(c,0))}</ul>{!practices.some(contains)&&<p className="preview-empty">No practices match this search.</p>}</div><div className="tree-selection" aria-live="polite"><strong>{selected.length} branch{selected.length===1?'':'es'} selected</strong><p>{selected.length?selected.map(id=>byId.get(id)?.display_name||id).join(' · '):'Select one or more branches above.'}</p><span>Included subtopics do not need another tick. Use an exclusion to skip a subtopic within a selected parent.</span></div></div>;
}
function TreeCheck({name,checked,partial,disabled,onChange}:{name:string;checked:boolean;partial:boolean;disabled:boolean;onChange:(v:boolean)=>void}){const ref=useRef<HTMLInputElement>(null);useEffect(()=>{if(ref.current)ref.current.indeterminate=partial;},[partial]);return <input ref={ref} type="checkbox" aria-label={`Follow ${name}`} checked={checked} disabled={disabled} onChange={e=>onChange(e.target.checked)}/>;}
