import {useEffect,useMemo,useState} from 'react';
import type {Concept,Profile,Update} from './types';
import {api,post,profileName,subscriptionAllowed,dateLabel} from './model';
import {Icon} from './icons';
import {ErrorBox,Modal,Loading} from './common';
import {PracticeTree} from './PracticeTree';
type Preview={total:number;reviewed_total:number;group_counts:Record<string,number>;updates:Update[]};
type Picker={index:number|'new'|'exclude';mode:'subject'|'narrow'|'exclude'};
export function Subscriptions({profile,concepts,onSaved,onDirty}:{profile:Profile;concepts:Concept[];onSaved:(p:Profile)=>void;onDirty:(dirty:boolean)=>void}){
 const [tree,setTree]=useState<string[]|null>(null);
 const [draft,setDraft]=useState<Profile>(structuredClone(profile)),[picker,setPicker]=useState<Picker|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [preview,setPreview]=useState<Preview|null>(null),[previewBusy,setPreviewBusy]=useState(true),[previewError,setPreviewError]=useState(''),[showAll,setShowAll]=useState(false);
 const dirty=JSON.stringify(draft)!==JSON.stringify(profile),valid=draft.rules.length>0&&draft.rules.every(r=>r.all_of.length>0);
 const byId=useMemo(()=>new Map(concepts.map(c=>[c.tag_id,c])),[concepts]);
 const name=(id:string)=>byId.get(id)?.display_name||id;
 useEffect(()=>{onDirty(dirty);},[dirty]);
 useEffect(()=>{setDraft(structuredClone(profile));setError('');},[profile]);
 useEffect(()=>{if(!valid){setPreview(null);setPreviewBusy(false);return;}const controller=new AbortController();setPreviewBusy(true);setPreviewError('');const timer=setTimeout(()=>{api<Preview>('/profiles/preview',{...post(draft),signal:controller.signal}).then(r=>{setPreview(r);setPreviewBusy(false);}).catch(e=>{if(e.name!=='AbortError'){setPreviewError('The preview could not be loaded. Your saved subscriptions have not changed.');setPreviewBusy(false);}});},300);return()=>{clearTimeout(timer);controller.abort();};},[draft,valid]);
 function change(d:Profile){setNotice('');changeDraft(d);}
 function changeDraft(d:Profile){setDraft(d);setShowAll(false);}
 function removeTag(index:number|'exclude',id:string){const d=structuredClone(draft);if(index==='exclude')d.exclude=d.exclude.filter(t=>t!==id);else d.rules[index].all_of=d.rules[index].all_of.filter(t=>t!==id);change(d);}
 async function save(){if(busy)return;setBusy(true);setError('');try{const result=await api<Profile>('/profiles',post(draft));onSaved(result);setNotice('Your interests are saved. For you now reflects these choices.');onDirty(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const chosen=picker?.index==='exclude'?draft.exclude:typeof picker?.index==='number'?draft.rules[picker.index]?.all_of||[]:[];
 function choose(id:string){if(!picker)return;const d=structuredClone(draft);if(picker.index==='new')d.rules.push({id:'interest-'+crypto.randomUUID().slice(0,8),all_of:[id]});else if(picker.index==='exclude'){if(!d.exclude.includes(id))d.exclude.push(id);}else if(picker.mode==='subject'){d.rules[picker.index].all_of=[id,...d.rules[picker.index].all_of.slice(1).filter(t=>t!==id)];}else if(!d.rules[picker.index].all_of.includes(id))d.rules[picker.index].all_of.push(id);change(d);setPicker(null);}
 return <div className="settings-page guided-settings"><header className="page-heading"><div className="eyebrow">YOUR PRACTICE</div><h1>Subscriptions</h1><p>A clear brief for the updates you want to receive.</p></header>
 <div className="subscription-intro"><div><span className="caption">FOLLOWING FOR</span><h2>{profileName(profile)}</h2></div><p>Choose a subject to follow broadly. Add another for wider coverage, or narrow an existing interest for a more focused feed.</p></div>
 <div className="settings-layout guided-layout"><div className="interest-editor"><div className="editor-section-title"><h2>Your interests</h2><button className="button secondary" onClick={()=>setTree(draft.rules.filter(r=>r.all_of.length===1&&byId.get(r.all_of[0])?.family==='Practice').map(r=>r.all_of[0]))}><Icon name="subscriptions" size={14}/> Browse practice tree</button></div>{error&&<ErrorBox message={error}/>}<div className="notice" role="status">{notice}</div>
 {draft.rules.map((rule,i)=>{const base=rule.all_of[0],children=concepts.filter(c=>c.parent===base).slice(0,5),refinements=rule.all_of.slice(1);return <div key={rule.id}>{i>0&&<div className="also-follow"><span>ALSO FOLLOW</span><p>This interest adds coverage. An update can match either interest.</p></div>}<section className="interest-group guided-group" aria-label={`Interest ${i+1}: ${base?name(base):'Choose a subject'}`}><div className="interest-heading"><div><div className="caption">INTEREST {i+1} <span>· {refinements.length?'Focused coverage':'Broad coverage'}</span></div><h3>{base?name(base):'Choose a subject'}</h3></div><button className="icon-button" aria-label={`Remove interest group ${i+1}`} onClick={()=>change({...draft,rules:draft.rules.filter((_,j)=>j!==i)})}><Icon name="close" size={16}/></button></div>
 <p className="scope-sentence">{base?<>You’ll receive updates about <strong>{name(base)}</strong>{refinements.length?<> only when the same provision also concerns <strong>{refinements.map(name).join(' and ')}</strong>.</>:<> and its more specific subtopics.</>}</>:'Choose one subject to start receiving relevant updates.'}</p>
 {base&&byId.get(base)?.definition&&<p className="subject-definition">{byId.get(base)?.definition}</p>}
 {children.length>0&&!refinements.length&&<div className="includes-line"><span>Includes</span><p>{children.map(c=>c.display_name).join(' · ')}{concepts.filter(c=>c.parent===base).length>5?' · and other subtopics':''}</p></div>}
 {!!refinements.length&&<div className="refinement-box"><span className="caption">ONLY WHEN IT ALSO CONCERNS</span><div className="interest-tags">{refinements.map(id=><span className="interest-tag" key={id}>{name(id)}<button aria-label={`Remove ${name(id)} from group ${i+1}`} onClick={()=>removeTag(i,id)}><Icon name="close" size={13}/></button></span>)}</div><p>Every choice must match the same provision. Adding a condition narrows this interest.</p></div>}
 <div className="group-actions"><button className="text-button" onClick={()=>setPicker({index:i,mode:'subject'})}>{base?'Change subject':'Choose a subject'} <Icon name="chevron" size={13}/></button>{base&&<button className="button secondary" onClick={()=>setPicker({index:i,mode:'narrow'})}><Icon name="filter" size={14}/>{refinements.length?'Add another condition':'Narrow this interest'}</button>}</div>
 {!refinements.length&&<p className="narrow-hint">Optional: narrow by regulation, topic, transaction or affected party.</p>}
 {preview&&!previewBusy&&<div className="group-count"><Icon name="updates" size={13}/>{preview.group_counts[rule.id]||0} matching reviewed update{preview.group_counts[rule.id]===1?'':'s'}{(preview.group_counts[rule.id]||0)===0&&<span> · Future updates may still match</span>}</div>}
 </section></div>;})}
 <button className="button secondary add-group" onClick={()=>setPicker({index:'new',mode:'subject'})}><Icon name="plus" size={16}/> Follow another subject</button><p className="add-group-hint">For example, follow debt markets alongside equity. Each interest works independently.</p>
 <details className="exclusions guided-exclusions" open={draft.exclude.length>0?true:undefined}><summary><span>Exclude topics</span><span className="caption">Optional{draft.exclude.length?` · ${draft.exclude.length} selected`:''}</span><Icon name="chevron" size={14}/></summary><p className="muted">Hide matching provisions even when they fit an interest. A document can still appear if a different provision matches.</p><div className="interest-tags">{draft.exclude.map(id=><span className="interest-tag" key={id}>{name(id)}<button aria-label={`Remove exclusion ${name(id)}`} onClick={()=>removeTag('exclude',id)}><Icon name="close" size={13}/></button></span>)}<button className="button dashed" onClick={()=>setPicker({index:'exclude',mode:'exclude'})}><Icon name="plus" size={15}/> Add exclusion</button></div></details>
 <div className="save-bar guided-save"><div><strong>{dirty?'Ready to update your feed?':'All changes saved'}</strong><p>{dirty?'Preview your choices, then save to apply them.':'These interests apply to this profile only.'}</p></div><div className="button-row"><button className="button secondary" disabled={!dirty||busy} onClick={()=>{changeDraft(structuredClone(profile));setNotice('');setError('');}}>Discard changes</button><button className="button primary" disabled={!dirty||!valid||busy} onClick={save}>{busy?'Saving…':'Save interests'}</button></div></div>{!valid&&<p className="error-text">Choose at least one subject before saving.</p>}
 </div><aside className="feed-preview"><div className="preview-heading"><Icon name="updates" size={18}/><h2>Your feed preview</h2></div><p className="preview-description">See how your choices apply to the reviewed documents already in ANS.</p><span className={`badge ${dirty?'proposed':''}`}>{dirty?'Unsaved selection':'Saved interests'}</span>
 {previewBusy?<Loading text="Checking your interests…"/>:previewError?<ErrorBox message={previewError}/>:!valid?<div className="preview-empty"><h3>Start with a subject</h3><p>Choose a practice, regulation or topic to see matching updates here.</p></div>:preview&&<><div className="preview-total" aria-live="polite"><strong>{preview.total} update{preview.total===1?'':'s'}</strong><span>match across {preview.reviewed_total} reviewed documents</span></div>{!preview.total?<div className="preview-empty"><h3>No current examples match</h3><p>Your interests may still match future documents. For broader coverage, remove a condition or choose a parent topic.</p></div>:<div className="preview-updates">{preview.updates.slice(0,showAll?100:3).map(u=><details key={u.id} className="preview-update"><summary><time>{dateLabel(u.published_date)}</time><h3>{u.title}</h3><span className="preview-why">Why it matches <Icon name="chevron" size={11}/></span></summary>{u.matches.map(m=><div className="preview-reason" key={m.rule_id+m.event_id}><span className="caption">Interest {draft.rules.findIndex(r=>r.id===m.rule_id)+1}</span><p>{m.reason}</p><strong>{m.event_title}</strong>{m.evidence?.[0]&&<a className="source-link" href={m.evidence[0].url!} target="_blank" rel="noreferrer">Source · page {m.evidence[0].pdf_page_start} <Icon name="external" size={12}/></a>}</div>)}</details>)}</div>}{preview.total>3&&<button className="text-button preview-more" onClick={()=>setShowAll(v=>!v)}>{showAll?'Show fewer':`Show all ${preview.total} updates`}</button>}<p className="footnote">An update matching several interests appears once. These counts describe the current collection, not future alert volume.</p></>}
 <div className="selection-help"><h3>How to choose</h3><p><strong>Follow broadly</strong><br/>Choose your practice or a parent topic to include its subtopics.</p><p><strong>Be more specific</strong><br/>Use “Narrow this interest” when you only want that subject for a particular regulation, transaction or party.</p><p><strong>Cover something else</strong><br/>Use “Follow another subject”. It adds an independent route into your feed.</p></div></aside></div>
 {tree!==null&&<Modal title="Choose your practice areas" close={()=>setTree(null)}><div className="picker-guidance"><p>Explore the complete practice hierarchy. Checked branches become separate interests. Your focused interests, non-practice choices and exclusions are kept.</p></div><PracticeTree concepts={concepts} selected={tree} onChange={setTree}/><footer className="modal-actions"><button className="button secondary" onClick={()=>setTree(null)}>Cancel</button><button className="button primary" onClick={()=>{const keep=draft.rules.filter(r=>r.all_of.length!==1||byId.get(r.all_of[0])?.family!=='Practice');const existing=new Map(draft.rules.filter(r=>r.all_of.length===1).map(r=>[r.all_of[0],r]));change({...draft,rules:[...keep,...tree.map(id=>existing.get(id)||{id:'interest-'+crypto.randomUUID().slice(0,8),all_of:[id]})]});setTree(null);}}>Apply selection</button></footer></Modal>}
 {picker&&<TagPicker concepts={concepts.filter(subscriptionAllowed)} selected={chosen} mode={picker.mode} subject={typeof picker.index==='number'?name(draft.rules[picker.index].all_of[0]):''} close={()=>setPicker(null)} choose={choose}/>}
 </div>;
}
function TagPicker({concepts,selected,mode,subject,close,choose}:{concepts:Concept[];selected:string[];mode:Picker['mode'];subject:string;close:()=>void;choose:(id:string)=>void}){
 const [q,setQ]=useState(''),[family,setFamily]=useState(mode==='subject'?'Practice':'');const families=[...new Set(concepts.map(c=>c.family||'Other'))];const visible=concepts.filter(c=>(!family||c.family===family)&&(!q||(c.display_name+' '+c.definition+' '+c.tag_id).toLowerCase().includes(q.toLowerCase())));
 return <Modal title={mode==='narrow'?'Make this interest more specific':mode==='exclude'?'Choose a topic to exclude':'What would you like to follow?'} close={close}><div className="picker-guidance"><p>{mode==='narrow'?<>Keep <strong>{subject}</strong>, but only include provisions that also match the choice below.</>:mode==='exclude'?'Matching provisions will be hidden, even if they fit one of your interests.':'Choose a broad practice for wider coverage, or search for a specific regulation, transaction or topic.'}</p>{mode==='narrow'&&<span>This narrows an existing interest. To cover a different subject independently, add another interest instead.</span>}</div><div className="picker-controls"><label className="search-box"><Icon name="search"/><span className="sr-only">Search interests</span><input autoFocus placeholder="Try IPO, LODR, mutual funds…" value={q} onChange={e=>{setQ(e.target.value);if(e.target.value)setFamily('');}}/></label><label className="sr-only" htmlFor="interest-family">Interest category</label><select id="interest-family" value={family} onChange={e=>setFamily(e.target.value)}><option value="">All categories</option>{families.map(f=><option key={f} value={f}>{f}</option>)}</select></div><div className="picker-results">{visible.length===0&&<p className="muted">No interests match. Try a broader subject or another term.</p>}{visible.map(c=>{const children=concepts.filter(x=>x.parent===c.tag_id);return <button disabled={selected.includes(c.tag_id)} className="picker-option" key={c.tag_id} onClick={()=>choose(c.tag_id)}><div><span className="caption">{c.family}{c.parent?' · '+(concepts.find(x=>x.tag_id===c.parent)?.display_name||'Subtopic'):''}</span><strong>{c.display_name}</strong><p>{c.definition}</p>{children.length>0&&<span className="picker-includes">Includes {children.slice(0,3).map(x=>x.display_name).join(', ')}{children.length>3?' and more':''}</span>}</div><Icon name={selected.includes(c.tag_id)?'check':'plus'} size={17}/></button>;})}</div><footer>{visible.length} choices · Your selections are applied only when you save</footer></Modal>;
}
