import {useEffect,useRef,useState} from 'react';
import type {Concept,Feed,Profile,Update} from './types';
import {api,dateLabel} from './model';
import {Icon} from './icons';
import {Loading,ErrorBox,Empty} from './common';
import {Detail} from './Detail';
export function Updates({profile,concepts,manage}:{profile:Profile;concepts:Concept[];manage:()=>void}){
 const [view,setView]=useState('for_you'),[q,setQ]=useState(''),[type,setType]=useState(''),[topics,setTopics]=useState<string[]>([]),[from,setFrom]=useState(''),[to,setTo]=useState(''),[filters,setFilters]=useState(false),[feed,setFeed]=useState<Feed|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[reload,setReload]=useState(0),[selected,setSelected]=useState<string|null>(null),[saving,setSaving]=useState<string[]>([]);
 const [narrow,setNarrow]=useState(()=>window.matchMedia('(max-width:1000px)').matches);
 useEffect(()=>{const media=window.matchMedia('(max-width:1000px)');const update=()=>setNarrow(media.matches);media.addEventListener('change',update);return()=>media.removeEventListener('change',update);},[]);
 const origin=useRef<HTMLElement|null>(null),results=useRef<HTMLDivElement>(null);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');const timer=setTimeout(()=>{const params=new URLSearchParams({profile_id:profile.id,view,q,limit:'100'});if(type)params.set('document_type',type);topics.forEach(t=>params.append('topic',t));if(from)params.set('date_from',from);if(to)params.set('date_to',to);api<Feed>('/updates?'+params,{signal:controller.signal}).then(x=>{setFeed(x);setLoading(false);}).catch(e=>{if(e.name!=='AbortError'){setError(e.message);setLoading(false);}});},180);return()=>{clearTimeout(timer);controller.abort();};},[profile.id,view,q,type,topics,from,to,reload]);
 useEffect(()=>{setSelected(null);results.current?.scrollTo(0,0);},[profile.id]);
 const active=topics.length+Number(!!type)+Number(!!from||!!to);
 async function state(id:string,value:{read?:boolean;saved?:boolean}){if(saving.includes(id))return;setSaving(x=>[...x,id]);try{const next=await api<Update['state']>(`/profiles/${profile.id}/documents/${id}/state`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)});setFeed(f=>f?{...f,updates:f.updates.map(x=>x.id===id?{...x,state:next}:x)}:f);if(view==='saved'&&value.saved===false)setReload(x=>x+1);}finally{setSaving(x=>x.filter(s=>s!==id));}}
 function open(id:string){origin.current=document.activeElement as HTMLElement;setSelected(id);state(id,{read:true}).catch(e=>setError(e.message));}
 function close(){setSelected(null);requestAnimationFrame(()=>origin.current?.focus());}
 function clear(){setQ('');setTopics([]);setType('');setFrom('');setTo('');}
 return <div className={`updates-layout ${selected?'with-detail':''}`}><div className="feed-pane" inert={!!selected&&narrow?true:undefined} aria-hidden={!!selected&&narrow?true:undefined}><header className="page-heading"><div className="eyebrow">SECURITIES REGULATION</div><h1>Regulatory updates</h1><p>Changes that matter to your practice.</p></header><div className="feed-controls"><div className="tabs-line"><div className="tabs" role="tablist" aria-label="Update collection">{[['for_you','For you'],['all','All updates'],['saved','Saved']].map(([v,label])=><button key={v} role="tab" aria-selected={view===v} onClick={()=>{setView(v);setSelected(null);}}>{label}</button>)}</div><button className="text-button manage" onClick={manage}>Manage interests <Icon name="arrow" size={14}/></button></div><div className="search-row"><label className="search-box"><Icon name="search"/><span className="sr-only">Search updates</span><input aria-label="Search updates" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search updates…"/>{q&&<button className="icon-button" onClick={()=>setQ('')} aria-label="Clear search"><Icon name="close" size={14}/></button>}</label><button className={`button secondary filter-toggle ${filters?'active':''}`} aria-label="Filters" aria-expanded={filters} onClick={()=>setFilters(x=>!x)}><Icon name="filter"/> Filters{active>0&&<span className="small-count">{active}</span>}</button></div>
 {filters&&<div className="filters"><label>Document type<select aria-label="Document type" value={type} onChange={e=>setType(e.target.value)}><option value="">All types</option>{concepts.filter(c=>c.tag_id.startsWith('DT_')).map(c=><option key={c.tag_id} value={c.tag_id}>{c.display_name}</option>)}</select></label><label>Add topic<select aria-label="Add topic" value="" onChange={e=>{if(e.target.value&&!topics.includes(e.target.value))setTopics([...topics,e.target.value]);}}><option value="">Select a topic</option>{concepts.filter(c=>c.tag_id.startsWith('TP_')).sort((a,b)=>a.display_name.localeCompare(b.display_name)).map(c=><option key={c.tag_id} value={c.tag_id}>{c.display_name}</option>)}</select></label><label>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label>{topics.length>0&&<div className="filter-chips">{topics.map(t=><button className="tag removable" key={t} onClick={()=>setTopics(topics.filter(x=>x!==t))}>{concepts.find(c=>c.tag_id===t)?.display_name}<Icon name="close" size={12}/><span className="sr-only">Remove topic</span></button>)}</div>}<button className="text-button" onClick={clear}>Reset filters</button></div>}
 <div className="results-label" aria-live="polite"><span>{loading?'Finding updates…':`${feed?.total||0} update${feed?.total===1?'':'s'}`}{view==='for_you'?' for your interests':''}</span><span>Newest first <Icon name="chevron" size={12} style={{transform:'rotate(90deg)'}}/></span></div></div>
 <div className="update-list" ref={results} aria-busy={loading}>{error?<ErrorBox message={error} retry={()=>setReload(x=>x+1)}/>:loading?<Loading/>:!feed?.updates.length?<><Empty title={view==='saved'&&!q&&!active?'Your saved updates will appear here':'No matching updates'} text={view==='saved'&&!q&&!active?'Use the bookmark beside an update to keep it here.':'Try changing your filters or broadening your subscriptions.'}/>{(q||active>0)&&<button className="button secondary empty-reset" onClick={clear}>Clear filters</button>}</>:feed.updates.map(u=><article key={u.id} className={`update-row ${selected===u.id?'selected':''} ${u.state.read?'read':''}`}><button className="update-open" onClick={()=>open(u.id)} aria-label={`Open ${u.title}`} aria-current={selected===u.id?'true':undefined}><div className="row-meta"><span className="type-label">{!u.state.read&&<span className="unread-dot"/>}{u.document_type.name}</span><time dateTime={u.published_date||undefined}>{dateLabel(u.published_date)}</time></div><h2>{u.title}</h2><p>{u.summary}</p><div className="row-bottom"><div className="tags">{u.topics.slice(0,2).map(t=><span className="tag" key={t.id}>{t.name}</span>)}{u.topics.length>2&&<span className="tag" title={u.topics.slice(2).map(t=>t.name).join(', ')}>+{u.topics.length-2}</span>}{u.has_proposals&&<span className="badge proposed">Includes proposals</span>}</div>{view==='for_you'&&<span className="match-indicator"><Icon name="check" size={13}/> Matches your interests</span>}</div></button><button className={`icon-button row-save ${u.state.saved?'is-saved':''}`} aria-label={`${u.state.saved?'Unsave':'Save'} ${u.title}`} aria-pressed={u.state.saved} disabled={saving.includes(u.id)} onClick={()=>state(u.id,{saved:!u.state.saved}).catch(e=>setError(e.message))}><Icon name="bookmark" size={17}/></button></article>)}</div></div>{selected&&<Detail id={selected} profile={profile} close={close} onState={state}/>}</div>;
}
